name = input()
shkav = int(input())
k = int(str(shkav)[0])
k1 = int(str(shkav)[2])
k2 = int(str(shkav)[1])
print(f"Группа №{k}.")
print(f"{k1}. {name}.")
print("Шкафчик: ", shkav, '.', sep="")
print(f"Кроватка: {k2}.")